### ISSUE TITLE
Topic "/klt_points" killed the launched node "visp_auto_tracker"

### ISSUE THREAD

**Issue by IhabMohamed** [lagadic/vision_visp#103]
Hi everyone,

I have a question regarding the **visp_auto_tracker** node. It works pretty well. However, when I tried to run ``rostopic echo /klt_points``, it kills the launched file (i.e., ``roslaunch visp_auto_tracker tutorial.launch``).

Any idea why this happened?
BTW, this is not the case when I run ``roslaunch visp_tracker tutorial.launch``

Many thanks in advance!

**Comment by fspindle** [comment]
The goal of this node is to give the pose of the object on topic `/visp_auto_tracker/object_position`. KLT keypoints are used internally by the tracker. There is no reason to publish their coordinates. The topic `/klt_point` is listed but shouldn't.

**Comment by IhabMohamed** [comment]
Many thanks for your response, I got your message.
