### ISSUE TITLE
Intel RealSense D435i with ROS package 'visp_auto_tracker': Pixel formats error !!!

### ISSUE THREAD

**Issue by datvtmkac** [lagadic/vision_visp#105]
Hi everyone,

I'm currently working with ROS package 'visp_auto_tracker' for tracking QR Code, this packge is really useful for me. I have done testing this pkg with some USB-Webcam (2D Logitech C270) and it worked really well. I've tried to use a different high quality camera, especially the Intel RealSense D435i for this stuff but I got these following issues:
1. These are logs: unknown control 'white_balance_temperature_auto'; 'focus_auto' in terminal console
2. Issue with Pixel formats of the D435i camera

I tried to fix it this by changing the node config in "tracklive_usb.launch" file. For usb camera acquisition node, I changed all available type of "pixel_format" parameter in this package but I expected RGB image mode did not come. Following the "usb_cam" node, there are 6 types of value available: 'yuyv', 'uyvy', 'mjpeg', 'yuvmono10', 'rgb24' and 'grey'.

Below here is content of "tracklive_usb.launch" file:
![visp_error_4](https://user-images.githubusercontent.com/70124479/93183017-a8436200-f764-11ea-836f-50db56ab0a2d.png)

And here are my following issues, I grab it in screenshots, sorry for this inconvenient:
![visp_error_3](https://user-images.githubusercontent.com/70124479/93181082-38cc7300-f762-11ea-9105-2de3600f7924.png)
![visp_error_2](https://user-images.githubusercontent.com/70124479/93181007-1d616800-f762-11ea-9867-0250cc755b77.png)

This image show RGB-Depth mode read, in RGB24 mode I got error, could not launch the camera and in Grey mode the color actually not right too.
![visp_error](https://user-images.githubusercontent.com/70124479/93180983-15092d00-f762-11ea-8b12-1038ea1dafbc.png)

So, I think my issues are about pixel formats of this Intel D435i camera, but I haven't solved it yet by myself. I hope you guys can give me a hand! Any help are very much appreciated!

Thanks,
datvt.

**Comment by datvtmkac** [comment]
I solved it. My mistake, sorry! I just used depth module instead RGB module. Now everything is fine!

**Comment by Gowresh-MARC** [comment]
Can you please share your launch file to use auto_tracker with D435i? I am trying to do the same, but not able to successfully.
