### ISSUE TITLE
visp_hand2eye_calibration:  Problem in solving Hand-Eye Calibration by VVS

### ISSUE THREAD

**Issue by aycameric** [lagadic/vision_visp#106]
Hello, 
I am using visp_hand2eye_calibration and have a few questions:
1. if I take six subsequent samples from my endeffector position, then there will not be much difference, since it takes a while with my spline cartesian controller and you said it's better to have a rotation in the poses, so I am saving six values with a user request. Is this right?
2. I get this error:  Problem in solving Hand-Eye Calibration by VVS
after I execute the calibration node.

Thank you in advance!
Best regards,

**Comment by aycameric** [comment]
And when I use the service I get this error:

Problem in solving Hand-Eye Rotation by Procrustes method 

Why is that?

**Comment by fspindle** [comment]
It means that with your data the algorithm is unable to converge.

This [image](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-calibration-extrinsic.html#calib_ext_acq_data) and the corresponding [tutorial](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-calibration-extrinsic.html) show what kind of good poses should be acquired to succeed.

**Comment by aycameric** [comment]
Does the algorithm use the AX=XB problem? And can I use it for eye-to-hand calibration instead of eye-in-hand? So I have a static camera position.. I solved the previous issue with better data but my matrix that I got is not correct.
