### ISSUE TITLE
ROS Markerless generic model-based tracking using AprilTag

### ISSUE THREAD

**Issue by sinasadeghian** [lagadic/vision_visp#115]
Hi,

Is there a ROS version of Markerless generic model-based tracking using AprilTag?
https://visp-doc.inria.fr/doxygen/visp-3.3.0/tutorial-tracking-mb-generic-apriltag-live.html#mb_generic_apriltag_webcam

Thank you,
Sina

**Comment by fspindle** [comment]
Sorry, no
