### ISSUE TITLE
Build Issue : colcon build vs colcon build --symlink-install 

### ISSUE THREAD

**Issue by v-snap** [lagadic/vision_visp#139]
Hi 
I tried building the package with `colcon build ` and was not able run the examples.
it throws error - unable to load shared library libvisp*.so

but with` colcon build --symlink-install ` it works fine.

**Comment by fspindle** [comment]
When visp libraries are not found you can set `LD_LIBRARY_PATH` with the folder that contains the libraries, like
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VISP_WS/visp-build/lib
```

Not tested, but should work.
