### ISSUE TITLE
vision_visp : build visp_hand2eye_calibration_calibrator fails

### ISSUE THREAD

**Issue by v-snap** [lagadic/vision_visp#140]
![Screenshot from 2024-06-26 21-16-08](https://github.com/lagadic/vision_visp/assets/55899089/5dd3a0bd-9ac9-4266-b8b0-3be48859d10d)

any help ?

**Comment by fspindle** [comment]
How do you build/install ViSP and which version ?

**Comment by v-snap** [comment]
I have built the visp from source 
Version 3.6.0

**Comment by aleciara** [comment]
Hello everyone,

I had a similar issue and resolved it by modifying the CMakeLists.txt files. For linking Boost libraries, I used the following approach:

`
find_package(Boost REQUIRED COMPONENTS 
  system 
  thread 
)

target_link_libraries(your_target_name
                      ${Boost_LIBRARIES})
`

I applied this method to the visp_camera_calibration, visp_hand2eye_calibration, visp_auto_tracker, and visp_ros packages.If this approach seems useful, I would be happy to assist.

Best,
Alessandro

**Comment by fspindle** [comment]
Should be fixed. Reopen if needed.
