### ISSUE TITLE
Can not use visp properly

### ISSUE THREAD

**Issue by zychaoqun** [lagadic/vision_visp#43]
Hello,

   I want to use the instrument visp to track the object,however,I encountered some problems which make me crazy.
1) I just download the by Source: git https://github.com/lagadic/vision_visp.git (branch: hydro) in opt/ros/hydro/share.  Then I try to launch the file in visp_tracker/tutorial.launch, however,there are always some problems like:
ERROR: cannot launch node of type [visp_tracker/tracker]: can't locate node [tracker] in package [visp_tracker]
ERROR: cannot launch node of type [visp_tracker/visp_tracker_client]: can't locate node [visp_tracker_client] in package [visp_tracker]
ERROR: cannot launch node of type [visp_tracker/visp_tracker_viewer]: can't locate node [visp_tracker_viewer] in package [visp_tracker]
###### 

Even I uninstall the linux and Ros ,it is all the same.
2.I try to install the visp from source, when I try to catkin_make the visp_auto_tracker in my catkin_ws,there is also problems like:
In file included from /home/chaoqun/catkin_ws/src/vision_visp/visp_auto_tracker/flashcode_mbt/detectors/qrcode/detector.cpp:1:0:
/home/chaoqun/catkin_ws/src/vision_visp/visp_auto_tracker/flashcode_mbt/detectors/qrcode/detector.h:9:18: fatal error: zbar.h: No such file or directory
compilation terminated.
make[2]: **\* [vision_visp/visp_auto_tracker/CMakeFiles/visp_auto_tracker_qrcode_detector.dir/flashcode_mbt/detectors/qrcode/detector.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [vision_visp/visp_auto_tracker/CMakeFiles/visp_auto_tracker_datamatrix_detector.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
make[1]: **\* [vision_visp/visp_auto_tracker/CMakeFiles/visp_auto_tracker_qrcode_detector.dir/all] Error 2
Linking CXX shared library /home/chaoqun/catkin_ws/devel/lib/libvisp_auto_tracker_cmd_line.so
[ 90%] Built target visp_auto_tracker_cmd_line
make: **\* [all] Error 2
Invoking "make" failed
###### 

I just do not know why,I really want to use this instrument,can you give me some hint?Thank you in advance!

**Comment by fspindle** [comment]
Closed.
Reopen if the issue remains.
