### ISSUE TITLE
Code does not look like it processes user config file.

### ISSUE THREAD

**Issue by rnunziata** [lagadic/vision_visp#45]
Code does not look like it processes user config file. It appears to over write user config file on input.
https://github.com/lagadic/visp_auto_tracker/blob/master/src/node.cpp

**Comment by fspindle** [comment]
Can you be more explicit

**Comment by rnunziata** [comment]
Lines 44-52 of node.cpp. Maybe I am missing something but it looks like if just over writes it. Sorry if I a  wrong.

**Comment by fspindle** [comment]
I will check

**Comment by fspindle** [comment]
For the moment the fix is in master branch. I want to introduce other improments before including everything in the devel branches and in the next ros packages. Could be ready end of the week.
