### ISSUE TITLE
visp_tracker Tutoral Broken?

### ISSUE THREAD

**Issue by ruffsl** [lagadic/vision_visp#47]
Hello,

I'm following the [Getting started](http://wiki.ros.org/visp_tracker/Tutorials/Getting%20started) tutorial of the [visp_tracker](http://wiki.ros.org/visp_tracker) package, and I believe I'm experience some unusual behavior when setting the initial pose from clicking on the UI client. Upon the second left mouse click for specifying the second vertex in the image, the GUI suddenly closes and reopens, where after a new image view renders a flickering pose estimate, presumably resulting from the unfinished pose initialization. The behavior is recorded the the gif bellow:
![anim](https://cloud.githubusercontent.com/assets/2293573/10865397/0840e616-7fe0-11e5-8a90-d9d073408ede.gif)

System info:
 * OS: Ubuntu 14.04 LTS
 * Distro: ROS Indigo
 * Package: ros-indigo-visp-tracker
  * Version: 0.8.1-0trusty-20150806-2245-+0000

**Comment by fspindle** [comment]
You do first a left click that validate a pose that is completely wrong.

You have rather to first right-click, then left-click on the 4 points (http://wiki.ros.org/visp_tracker/Tutorials/Getting%20started#Setting_the_initial_pose) to initialize the pose.
