### ISSUE TITLE
Cannot download tutorial-qrcode.bag ,could you please upload it to the github directly?

### ISSUE THREAD

**Issue by YuxiHuang001** [lagadic/vision_visp#49]
While I catkin_make the packages the downloading speed is very very slow,I don't know why .But the speed while I surffing other website is normal.Maybe it is the reason that I cannot visit that website normally.So could you please upload it to the github directly?Thx a lot.

**Comment by fspindle** [comment]
The bag is available here: https://github.com/lagadic/vision_visp/releases/download/vision_visp-0.5.0/tutorial-qrcode.bag
