### ISSUE TITLE
Is there any way to speed up visp_auto_tracker?

### ISSUE THREAD

**Issue by zkuan** [lagadic/vision_visp#50]
I am using the indigo branch to track a QR code. But the detection and redetection process take a lot of time. So is there any way to optimize the code, such as multi-thread program? And how to make it possible? I am sorry for my poor English and thanks in advance.

**Comment by fspindle** [comment]
The only way I see is to build in Release if this is not done

    $ catkin_make -DCMAKE_BUILD_TYPE=Release

**Comment by zkuan** [comment]
@fspindle It has been done already. Thanks anyway.
