### ISSUE TITLE
ROS Wiki pages not working

### ISSUE THREAD

**Issue by 9a3eedi** [lagadic/vision_visp#53]
Hi,

The ROS wiki pages are not working. It seems to appear while it's loading but then it disappears. Here's an example, although it's not the only one.
http://wiki.ros.org/visp

I first posted this issue in the ROS forums and I was directed to post the issue here. It looks like there's something wrong with the way macros are used in the wiki
http://answers.ros.org/question/236763/visp-wiki-pages-not-working/?answer=236812#post-id-236812

**Comment by fspindle** [comment]
Thanks for your feedback. I will try to fix that once wiki.ros.org becomes reachable.
