### ISSUE TITLE
how to make different object to track.

### ISSUE THREAD

**Issue by zubair123khan** [lagadic/vision_visp#61]
hi, 
i am trying to use this, but its just showing image from my camera driver,, how can i make a specific object to track from this  .. ???

**Comment by fspindle** [comment]
There is this [tutorial](http://wiki.ros.org/visp_tracker/Tutorials/Tracking%20your%20own%20model) that I have just updated.

**Comment by zubair123khan** [comment]
Thanks a lot.... I will look at it ..

**Comment by Choco83** [comment]
From what I have seen qr detection can be tricky at bug distance. I tried aruco marker and it worked pretty well. If I want to track a specific aruco marker using visp, any pointers on that?

**Comment by ziggBee30** [comment]
,
