### ISSUE TITLE
Calibration problem for webcam

### ISSUE THREAD

**Issue by henryng375** [lagadic/vision_visp#84]
Now, I'm using logitech webcam C525. Try to do calibration and follow [http://wiki.ros.org/visp_camera_calibration/Tutorials/CalibrationExternalCamera](url) for External Camera. But the problem is this only for IIDC 1394-based Digital Camera. Is there any calibration method for webcam? Thanks.

**Comment by fspindle** [comment]
You have to use `usb_cam` [[1](http://wiki.ros.org/usb_cam)] node instead of `camera1394` node replacing the line:

````
  <node pkg="camera1394" type="camera1394_node" name="my_camera1394_node" args="_video_mode:=640x480_mono8"/>
````
