### ISSUE TITLE
Sensitive tracking how to change " range " parameter ? 

### ISSUE THREAD

**Issue by jadhm** [lagadic/vision_visp#86]
Hi,

First of all, thank you very much for such a useful package. 
I would like to ask about the sensitivity of tracking the Qr code, I saw in other issues that changing the range could help but I couldn't find where  I can find this parameter. Could someone tell me where exactly I can find it to increase it. 
Another question how the z distance is calculated since you are not using a depth camera ? 
Thanks in advance.

Jad

**Comment by fspindle** [comment]
For the tracker parameters you should have a look to the [tutorial](http://wiki.ros.org/visp_tracker/Tutorials/Fine%20tuning%20of%20the%20tracking%20parameters)

The 3D is estimated thanks to the 3D model of the object.
