### ISSUE TITLE
Release to ROS melodic and there are errors in vision_visp/visp_tracker/src/notelets

### ISSUE THREAD

**Issue by ShutingKANG** [lagadic/vision_visp#88]
I am really want to ask will you give the release of vision_visp for ROS melodic?  when I install the vision_visp from source code for melodic,there is always some mistake. And i don't find the solution for these problems. so I am really hope you can releasse of vision_visp and visp_ros for ROS melodic.

When I build the vision_visp the problem is :    
  
home/user/catkin_ws/src/vision_visp/visp_tracker/src/nodelets/client.cpp:59:24: 
error: expected constructor, destructor, or type conversion before ‘(’ token
 PLUGINLIB_DECLARE_CLASS(visp_tracker, TrackerClient, visp_tracker::TrackerClientNodelet, nodelet::Nodelet);

/home/user/catkin_ws/src/vision_visp/visp_tracker/src/nodelets/viewer.cpp:59:24: 
error: expected constructor, destructor, or type conversion before ‘(’ token
 PLUGINLIB_DECLARE_CLASS(visp_tracker, TrackerViewer, visp_tracker::TrackerViewerNodelet, nodelet::Nodelet);

/home/user/catkin_ws/src/vision_visp/visp_tracker/src/nodelets/tracker.cpp:61:24: 
error: expected constructor, destructor, or type conversion before ‘(’ token
 PLUGINLIB_DECLARE_CLASS(visp_tracker, Tracker, visp_tracker::TrackerNodelet, nodelet::Nodelet);
 
I think maybe the problem is  PLUGIN_DECLARE_CLASS can't be used. I have tried to change it in PLUGIN_EXPORT_ClASS， but there are also errors.  I also tried to use plugin_macro_update, but the error is that cannot find this command. so I really don't know how to solve it. 

I'm really hope someone can help me. Thank you for your help.

**Comment by fspindle** [comment]
Releasing for Melodic is in the roadmap.
I will work on that asap...

**Comment by ShutingKANG** [comment]
> Releasing for Melodic is in the roadmap.
> I will work on that asap...

Thank you for your reply. Maybe I have solved this question by changing  the PLUGIN_DECLEARE_CLASS to PLUGIN_EXPORT_ClASS， the PLUGIN_EXPORT_ClASS use only two parameter.
