### ISSUE TITLE
Keypoint detection for ROS

### ISSUE THREAD

**Issue by orz-000** [lagadic/vision_visp#92]
Hello,
I want keypoint based detection.
https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-detection-object.html
I don't want to use qr code, so I seek this pkg for ros, but I can't find ros pkg of this detection, are there keypoint based object detection for ROS?

**Comment by fspindle** [comment]
Sorry, but this is no corresponding ros package yet.

**Comment by orz-000** [comment]
Thank you for your reply.
