### ISSUE TITLE
Wrong License Listed on  wiki.ros.org

### ISSUE THREAD

**Issue by rittersb** [lagadic/vision_visp#95]
On the [wiki](http://wiki.ros.org/vision_visp) for this package the license is listed as BSD, however the code is licensed under the GPL-2.

**Comment by fspindle** [comment]
Thanks for your feedback.
You are right the package you pointed out is GPL v2 as well as [visp_tracker](http://wiki.ros.org/visp_tracker) package.

I will release again asap.
